### PR TITLE
Fixes backgroundPosition declaration

### PR DESCRIPTION
**Pull request by jsiebern**
Not sure if I'm missing anything but I think it needs to accept 2 arguments

### CODE REVIEW

**Comment by alexfedoseev** [comment]
Ah, I missed that. According to MDN, it's possible to apply from 1 to 4 arguments, so it's better to add 3 more functions: `backgroundPosition2`, `backgroundPosition3` & `backgroundPosition4`.

https://developer.mozilla.org/en-US/docs/Web/CSS/background-position

**Comment by jsiebern** [comment]
Right, I'll fix that!

My first thought was adding something like this to `re-css` as well (for using the `top`, etc.)

```ml
module BackgroundPosition = {
  module PositionX = {
    type t = [ | `left | `right | `center];

    let toString = (x: t) =>
      switch (x) {
      | `left => "left"
      | `right => "right"
      | `center => "center"
      };
  };
  module PositionY = {
    type t = [ | `top | `bottom | `center];

    let toString = (x: t) =>
      switch (x) {
      | `top => "top"
      | `bottom => "bottom"
      | `center => "center"
      };
  };

  type t = [
    | `size(LengthPercentage.t, LengthPercentage.t)
    | `xy(PositionX.t, PositionY.t)
    | `initial
  ];

  let toString = (x: t) =>
    switch (x) {
    | `size(x, y) =>
      let x = x->LengthPercentage.toString;
      let y = y->LengthPercentage.toString;
      {j|$x $y|j};
    | `xy(x, y) =>
      let x = x->PositionX.toString;
      let y = y->PositionY.toString;
      {j|$x $y|j};
    | `initial => "initial"
    };
};
```

Is that all representable by simple percentage values?

**Comment by jsiebern** [comment]
For the `2, 3, 4` solution, it would need to be just one arg then per variant. Overkill or the way to go?

**Comment by jsiebern** [comment]
And theres multiple images to consider as well, so same as `backgroundSize` we should add `backgroundPositions`.

Lmk your thoughts and I'm happy to implement the changes

**Comment by alexfedoseev** [comment]
Thanks a bunch 👍

**Comment by alexfedoseev** [comment]
🎯

**Comment by alexfedoseev** [comment]
Published `re-css@v0.0.4`, can you bump it here?

**Comment by alexfedoseev** [comment]
Thanks!

**Pull request merged**
